### ISSUE TITLE
Finalize core repository for a bootable system

### ISSUE THREAD

**Issue by dylanaraps** [kissx/packages#12]
### Package status

chroot:
- [x] autoconf
- [x] baselayout
- [x] binutils
- [x] bison
- [x] busybox
- [x] ca-certificates
- [x] curl
- [x] e2fsprogs (busybox doesn't provide mkfs.ext3/4)
- [x] file
- [x] flex
- [x] gcc
- [x] git
- [x] gmp
- [x] kiss
- [x] libarchive
- [x] libressl
- [x] linux-headers
- [x] m4
- [x] make
- [x] mpc1
- [x] mpfr
- [x] musl
- [x] perl
- [x] pkgconf
- [x] sudo
- [x] xz
- [x] zlib

bootable system:
- [x] automake
- [x] baseinit
- [x] grub
- [x] libelf (non-elfutils, old version)
- [x] libnl3
- [x] linux
- [x] linux-firmware
- [x] wpa_supplicant

**Comment by konimex** [comment]
For a *bootable* system you really only need `sh` and a working Linux kernel, that's it. I've tried in an LFS instance, (but you can't do anything useful there).

However if you want it to be usable of course `busybox` should exist, the libc should exist, maybe libressl and also ca-certificates for HTTPS `wget`. Also if we want to compile then binutils, gcc, and make are the most essential packages, but maybe we can throw in almost all of Arch's `base-devel` or Void's [`base-devel`](http://termbin.com/8suu). I think how *should* we define core can be done after we finally boot the system successfully.

**Comment by dylanaraps** [comment]
Yeah, I meant a usable system and by usable I meant including the tools necessary to build and install packages. `busybox` gives us a lot of the separate packages in the above `devel` repositories which is nice.

I've updated the permissions for members and you should be able to push to master now.

**Comment by konimex** [comment]
Before we make a full usable `chroot`/bootable system, we would need a filesystem hierarchy.

The "standard" is of course, [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard), but if you have any changes you want to make, please say so. Also, should we merge `/bin` and `/usr/bin` (`/bin`, `/sbin`, `/usr/sbin` linking to `/usr/bin`)? Should we merge `/lib` and `/usr/lib`? For 64-bit systems, should we link `/usr/lib64` to plain `/usr/lib`? Should we combine `/usr/lib` and `/usr/libexec`?

Also, we'll need skeleton "base" files like `/etc/profile`, `/etc/hosts`, `/etc/crypttab`, `/etc/fstab`, `/etc/passwd`, etc. We would need to add a package (like Void `base-files`, or CRUX/Arch `filesystem`, or Gentoo/Alpine `baselayout`) for this. I'll make all of these later.

**Comment by dylanaraps** [comment]
I'd like to make the hierarchy as simple as possible. Do you think `symlinking` the `bin` directories is simpler than separating them?

**Comment by dylanaraps** [comment]
`patch` conflicts with `busybox`'s `patch`. Shall we compile `busybox` without `patch` or use `busybox`'s `patch` instead?

**Comment by konimex** [comment]
>Is it possible to simplify things even further and just have a `/bin` for binaries for example?

That's the suckless(.org) way, but IIRC for compatibility reasons it isn't used by other distros. (That's why the symlink is `/bin` to -> `/usr/bin` and not the other way).

>I'd like to make the hierarchy as simple as possible. Do you think symlinking the `bin` directories is simpler than separating them?

Honestly, "simple" is a very broad concept. But since we'd only deal with one directory `/usr/bin`, it'd be of course, "simpler".

**Comment by dylanaraps** [comment]
Symlinks work fine then. :+1:

**Comment by konimex** [comment]
[baselayout](https://github.com/kissx/packages/commit/17703e1e6e28054bed3e67b0da93c01c1c4dd931) has been added, this will be the foundation for KISS Linux (maybe `musl` should depend on this).

If you have any changes you want to make, feel free to commit.

**Comment by dylanaraps** [comment]
Installation of `baselayout` fails when it is installed on top of an existing hierarchy. It also fails when re-installed.

**Comment by konimex** [comment]
>Installation of `baselayout` fails when it is installed on top of an existing hierarchy. 

Since on an existing hierarchy `/bin` (e.g. busybox) or `/usr/lib64` (e.g. gcc) are not symlinks, it is bound to fail. A new fresh `kiss-chroot` would be needed with `baselayout` as the very base package.

>It also fails when re-installed.

Yes, I get that too. For some reason it doesn't remove the symlinks. Also since `/etc` files aren't removed and the tar extraction will fail since it already exists. [Here are my logs](https://termbin.com/zizo).

**Comment by dylanaraps** [comment]
The errors about files already existing in `/etc` are intentional since we use `tar` with `k`. Maybe an additional check is required for `pkg_remove` to use `unlink`.

**Comment by konimex** [comment]
For symlinks a plain `rm` should work, no?

**Comment by dylanaraps** [comment]
Packages failing to build on my system in the KISS `chroot`:

**`flex`**:

```
Making install in src
make[1]: Entering directory '/root/.cache/kiss/build-7818/src'
make[2]: Entering directory '/root/.cache/kiss/build-7818/src'
 ../build-aux/install-sh -c -d '/root/.cache/kiss/pkg-7818/usr/lib'
 ../build-aux/install-sh -c -d '/root/.cache/kiss/pkg-7818/usr/include'
 /bin/sh ../libtool   --mode=install /bin/install -c   libfl.la '/root/.cache/kiss/pkg-7818/usr/lib'
 /bin/install -c -m 644 FlexLexer.h '/root/.cache/kiss/pkg-7818/usr/include'
libtool: install: /bin/install -c .libs/libfl.so.2.0.0 /root/.cache/kiss/pkg-7818/usr/lib/libfl.so.2.0.0
install: can't stat '.libs/libfl.so.2.0.0': No such file or directory
make[2]: *** [Makefile:597: install-libLTLIBRARIES] Error 1
make[2]: Leaving directory '/root/.cache/kiss/build-7818/src'
make[1]: *** [Makefile:1557: install-am] Error 2
make[1]: Leaving directory '/root/.cache/kiss/build-7818/src'
make: *** [Makefile:533: install-recursive] Error 1
```

**`gmp`**:

```
g++: error: ./.libs/libgmp.so: No such file or directory
make[2]: *** [Makefile:869: libgmpxx.la] Error 1
make[2]: Leaving directory '/root/.cache/kiss/build-12122'
make[1]: *** [Makefile:956: all-recursive] Error 1
make[1]: Leaving directory '/root/.cache/kiss/build-12122'
make: *** [Makefile:775: all] Error 2
```

**Comment by konimex** [comment]
I'm not sure what caused the error, since it means somehow when compiling `curl`, `gmp`, and `flex` can't even find their own compiled file. Try to use the new tarball I uploaded, [this one](https://github.com/kissx/packages/releases/download/0.0.2-musl/kiss-chroot.tar.xz).

This is my `flex` log, specifically the `libfl.so` part:

```
Making install in src
make[1]: Entering directory '/root/.cache/kiss/build-18409/src'
make[2]: Entering directory '/root/.cache/kiss/build-18409/src'
 ../build-aux/install-sh -c -d '/root/.cache/kiss/pkg-18409/usr/lib'
 ../build-aux/install-sh -c -d '/root/.cache/kiss/pkg-18409/usr/include'
 /bin/sh ../libtool   --mode=install /usr/bin/install -c   libfl.la '/root/.cache/kiss/pkg-18409/usr/lib'
 /usr/bin/install -c -m 644 FlexLexer.h '/root/.cache/kiss/pkg-18409/usr/include'
libtool: install: /usr/bin/install -c .libs/libfl.so.2.0.0 /root/.cache/kiss/pkg-18409/usr/lib/libfl.so.2.0.0
libtool: install: (cd /root/.cache/kiss/pkg-18409/usr/lib && { ln -s -f libfl.so.2.0.0 libfl.so.2 || { rm -f libfl.so.2 && ln -s libfl.so.2.0.0 libfl.so.2; }; })
libtool: install: (cd /root/.cache/kiss/pkg-18409/usr/lib && { ln -s -f libfl.so.2.0.0 libfl.so || { rm -f libfl.so && ln -s libfl.so.2.0.0 libfl.so; }; })
libtool: install: /usr/bin/install -c .libs/libfl.la /root/.cache/kiss/pkg-18409/usr/lib/libfl.la
```

This is my log for `gmp`: https://termbin.com/7u7d

and this one is `curl`: https://termbin.com/30rq

**Comment by dylanaraps** [comment]
Those errors are with the new tarball.

**Comment by konimex** [comment]
I've updated the issue to reflect the current status of the packages and updated the title to reflect our current aim. For chroot system, the 20 packages should be enough to rebuilt the very "nucleus" system. For a bootable system, so far we have 4 packages.

**Comment by konimex** [comment]
For a core system, I took these list from Void `base-system`:
- acpid
- <s>base-files</s> (baselayout)
- <s>bash</s> (busybox ash)
- btrfs-progs
- <s>coreutils</s> (busybox)
- <s>dash</s> (busybox)
- <s>dhcpcd</s> (busybox udhcpc)
- <s>diffutils</s> (busybox)
- <s>dosfstools</s> (busybox)
- <s>e2fsprogs</s>
- ethtool
- <s>eudev</s> (mdev)
- f2fs-tools
- <s>file</s>
- <s>findutils</s> (busybox)
- <s>gawk</s> (busybox awk)
- <s>grep</s> (busybox)
- <s>gzip</s> (busybox gzip)
- iana-etc
- <s>iproute2</s> (busybox)
- <s>iputils</s> (busybox)
- kbd
- <s>kmod</s> (busybox)
- <s>less</s> (busybox)
- <s>libgcc</s> (gcc)
- man-pages
- <s>nvi</s> (busybox vi)
- openssh
- <s>pciutils</s> (busybox)
- <s>procps-ng</s> (busybox)
- <s>psmisc</s> (busybox)
- <s>runit-void</s> (baseinit)
- <s>sed</s> (busybox)
- <s>shadow</s> (busybox)
- sudo
- <s>tar</s> (busybox)
- <s>traceroute</s> (busybox)
- tzdata
- <s>usbutils</s> (busybox)
- <s>util-linux</s> (busybox)
- <s>which</s> (busybox)
- <s>wpa_supplicant</s>
- xfsprogs

In addition to the Void packages, Arch also has this list on their `base`:
- cryptsetup
  makedepends: device-mapper, json-c, libressl, popt, libargon2, pkgconf
- device-mapper (part of lvm2)
- gettext (unneeded in musl?)
- <s>inetutils</s> (busybox)
- jfsutils
- logrotate
- lvm2
  we'll need to check manually as sources differ on this one
- <s>man-db</s> (busybox)
- man-pages
- mdadm
  makedepends: linux-headers
- nano
- <s>perl</s>
- reiserfsprogs
- <s>s-nail</s> (busybox)
- sysfsutils
- <s>texinfo</s> (unneeded)

We have few options:
- Adding them to `core` and install them on system by default
- Adding them to `core`, but make it optional to install
- Don't add them to `core`.

**Comment by dylanaraps** [comment]
`busybox` provides `acpid` too.

**Comment by dylanaraps** [comment]
- `brtfs-utils`:
    - [ ] `libblkid`
    - [ ] `liblzo2`
    - [ ] `libzstd`
    - [x] `zlib`
    - [ ] `libreiserfscore`
    - [x] `e2fsprogs`
    - [ ] `libattr` (Supposed to be in your `libc`, does `musl` have this?)

**Comment by konimex** [comment]
- `tzdata` is needed for non-UTC timezones.
- `kbd` is probably needed for non-US keyboards.
- `iana-etc` stores all known internet protocols, probably needed.
- `f2fs` is probably used by SSD filesystems, but we can still keep them out of `core`.

As for `btrfs-progs` and `reiserfsprogs`, maybe we can keep them out of `core`, btrfs for reason you listed, and I don't think anyone uses reiserfs.

**Comment by dylanaraps** [comment]
Core *should* be finalized. Will open new issue for Extra.

**Comment by neoraindaemon** [comment]
> For a _bootable_ system you really only need `sh` and a working Linux kernel, that's it. I've tried in an LFS instance, but of course you can't do anything useful there.
> 
> However if you want it to be usable of course `busybox` should exist, the libc should exist, maybe libressl and also ca-certificates for HTTPS `wget`. Also if we want to compile then binutils, gcc, and make are the most essential packages, but maybe we can throw in almost all of Arch's `base-devel` or Void's [`base-devel`](http://termbin.com/8suu). I think how _should_ we define core can be done after we finally boot the system successfully.

Void's void-basestrap is lighter than its typical base package, for what it's worth.
