### ISSUE TITLE
Finalizing Extra

### ISSUE THREAD

**Issue by dylanaraps** [kissx/packages#13]
Packages (so far):

- [ ] cryptsetup
- [ ] json-c
- [ ] libaio
- [ ] lvm2
- [ ] openssh
- [ ] popt
- [ ] tlp

**Comment by konimex** [comment]
I'm closing this issue as we can add packages to `extra` on a case-by-case basis. `extra` is more than likely to be a dynamic repo unlike `core` thus can't be really "finalized".
