### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by shizonic** [kissx/packages#25]
I really love this project and would like to get involved by contributing. I love shell scripting (especially POSIX sh) and use your pure bash bible regularly. Further I am package maintainer for some packages of voidlinux and packaged for archlinux in the past. So I am not a beginner I guess.

Is there any way to get involved?

**Comment by dylanaraps** [comment]
I'm writing a general contribution guide which will live on the website. If you'd like to get involved in the actual development of KISS, join the Discord server and start chatting. Work is being done to get `rust` and `go` packaged as of now. I'm also working on writing pages for the new website.

**Comment by shizonic** [comment]
This sound great. I really thought more about getting involved into the current development process. So I would like to join Discord. What is the server invitation?

**Comment by dylanaraps** [comment]
https://discord.gg/YRwnHgH
